from alembic import op
from sqlalchemy.sql.schema import Column
from sqlalchemy.sql.schema import ForeignKeyConstraint
from sqlalchemy.sql.schema import MetaData
from sqlalchemy.sql.schema import PrimaryKeyConstraint
from sqlalchemy.sql.schema import Table
from sqlalchemy.sql.sqltypes import DateTime
from sqlalchemy.sql.sqltypes import Integer
from sqlmodel.sql.sqltypes import AutoString

# revision identifiers, used by Alembic.
revision = 'JhXElUEXmTxyv7gNDI4MEQ'
down_revision = 'Jl0V03IHpTZ2yoqhlVYkctg'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by rewire_sqlmodel - please adjust! ###
    op.create_table(
        'reviewrequestplatformlink',
        Column(
            'review_request_id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'platform_id',
            AutoString(),
            primary_key=True,
            nullable=False,
        ),
        ForeignKeyConstraint(
            ['platform_id'],
            [
                'platform.id',
            ],
            name='fk_reviewrequestplatformlink_platform_id_platform',
        ),
        PrimaryKeyConstraint(
            'review_request_id',
            'platform_id',
        ),
        ForeignKeyConstraint(
            ['review_request_id'],
            [
                'reviewrequest.id',
            ],
            name='fk_reviewrequestplatformlink_review_request_id_reviewrequest',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by rewire_sqlmodel - please adjust! ###
    op.drop_table('reviewrequestplatformlink')
    # ### end Alembic commands ###


_Meta = MetaData()
schema = {
    'aspect': Table(
        'aspect',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'name',
            AutoString(),
            nullable=False,
        ),
        PrimaryKeyConstraint(
            'id',
        ),
    ),
    'doctor': Table(
        'doctor',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'name',
            AutoString(),
            nullable=False,
        ),
        Column(
            'specialty',
            AutoString(),
            nullable=False,
        ),
        PrimaryKeyConstraint(
            'id',
        ),
    ),
    'platform': Table(
        'platform',
        _Meta,
        Column(
            'id',
            AutoString(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'name',
            AutoString(),
            nullable=False,
        ),
        Column(
            'image_path',
            AutoString(),
            nullable=False,
        ),
        PrimaryKeyConstraint(
            'id',
        ),
    ),
    'reviewrequest': Table(
        'reviewrequest',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'created_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'user_fio',
            AutoString(),
            nullable=True,
        ),
        Column(
            'user_phone',
            AutoString(),
            nullable=True,
        ),
        Column(
            'generated_text',
            AutoString(),
            nullable=True,
        ),
        PrimaryKeyConstraint(
            'id',
        ),
    ),
    'service': Table(
        'service',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'name',
            AutoString(),
            nullable=False,
        ),
        PrimaryKeyConstraint(
            'id',
        ),
    ),
    'doctorservicelink': Table(
        'doctorservicelink',
        _Meta,
        Column(
            'doctor_id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'service_id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        PrimaryKeyConstraint(
            'doctor_id',
            'service_id',
        ),
        ForeignKeyConstraint(
            ['service_id'],
            [
                'service.id',
            ],
            name='fk_doctorservicelink_service_id_service',
        ),
        ForeignKeyConstraint(
            ['doctor_id'],
            [
                'doctor.id',
            ],
            name='fk_doctorservicelink_doctor_id_doctor',
        ),
    ),
    'reviewrequestaspectlink': Table(
        'reviewrequestaspectlink',
        _Meta,
        Column(
            'review_request_id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'aspect_id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        PrimaryKeyConstraint(
            'review_request_id',
            'aspect_id',
        ),
        ForeignKeyConstraint(
            ['review_request_id'],
            [
                'reviewrequest.id',
            ],
            name='fk_reviewrequestaspectlink_review_request_id_reviewrequest',
        ),
        ForeignKeyConstraint(
            ['aspect_id'],
            [
                'aspect.id',
            ],
            name='fk_reviewrequestaspectlink_aspect_id_aspect',
        ),
    ),
    'reviewrequestdoctorlink': Table(
        'reviewrequestdoctorlink',
        _Meta,
        Column(
            'review_request_id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'doctor_id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        PrimaryKeyConstraint(
            'review_request_id',
            'doctor_id',
        ),
        ForeignKeyConstraint(
            ['review_request_id'],
            [
                'reviewrequest.id',
            ],
            name='fk_reviewrequestdoctorlink_review_request_id_reviewrequest',
        ),
        ForeignKeyConstraint(
            ['doctor_id'],
            [
                'doctor.id',
            ],
            name='fk_reviewrequestdoctorlink_doctor_id_doctor',
        ),
    ),
    'reviewrequestplatformlink': Table(
        'reviewrequestplatformlink',
        _Meta,
        Column(
            'review_request_id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'platform_id',
            AutoString(),
            primary_key=True,
            nullable=False,
        ),
        ForeignKeyConstraint(
            ['review_request_id'],
            [
                'reviewrequest.id',
            ],
            name='fk_reviewrequestplatformlink_review_request_id_reviewrequest',
        ),
        ForeignKeyConstraint(
            ['platform_id'],
            [
                'platform.id',
            ],
            name='fk_reviewrequestplatformlink_platform_id_platform',
        ),
        PrimaryKeyConstraint(
            'review_request_id',
            'platform_id',
        ),
    ),
    'reviewrequestservicelink': Table(
        'reviewrequestservicelink',
        _Meta,
        Column(
            'review_request_id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'service_id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        ForeignKeyConstraint(
            ['service_id'],
            [
                'service.id',
            ],
            name='fk_reviewrequestservicelink_service_id_service',
        ),
        PrimaryKeyConstraint(
            'review_request_id',
            'service_id',
        ),
        ForeignKeyConstraint(
            ['review_request_id'],
            [
                'reviewrequest.id',
            ],
            name='fk_reviewrequestservicelink_review_request_id_reviewrequest',
        ),
    ),
}
